version: '1.0'

services:
  web:
    build:
      context: .
      dockerfile: Dockerfile
    container_name: fiap-fast-food-service
    ports:
      - "3000:3000"
    depends_on:
      - db

  db:
    image: postgres
    container_name: postgres-fiapff
    restart: always
    environment:
      POSTGRES_USER: admin
      POSTGRES_PASSWORD: 1qazxsw@
      POSTGRES_DB: fiap_fast_food
    ports:
      - 5432:5432
